/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112092-g27562bf022-20230915"
#endif /* AVUTIL_FFVERSION_H */
